"""People counting, restricted-area, heatmap, and queue analytics."""

from app.analytics.counting import (
    CameraCountingConfig,
    CountingResult,
    CountingSnapshot,
    LineCount,
    OccupancyCount,
    PeopleCounter,
)
from app.analytics.visualization import annotate_people_counts
from app.analytics.restricted_area import (
    CameraRestrictedAreaConfig,
    IntrusionState,
    IntrusionTrackStatus,
    RestrictedAreaDetector,
    RestrictedAreaResult,
    RestrictedAreaSnapshot,
    RestrictedZoneStatus,
)
from app.analytics.restricted_visualization import annotate_restricted_areas
from app.analytics.heatmap import (
    CrowdedRegion,
    HeatmapAccumulator,
    HeatmapExportPaths,
    HeatmapGrid,
    HeatmapSnapshot,
    HeatmapVideoPaths,
    HeatmapVideoWriter,
    MovementHeatmaps,
    MovementHeatmapSnapshot,
    annotate_crowded_regions,
    colorize_heatmap,
    export_heatmap_snapshot,
    export_numeric_grid,
    overlay_heatmap,
    rank_crowded_regions,
)
from app.analytics.queue import (
    CameraQueueConfig,
    QueueAnalyzer,
    QueueResult,
    QueueSnapshot,
    QueueStatus,
    QueueTrackState,
    QueueTrackStatus,
)
from app.analytics.queue_visualization import annotate_queues
from app.analytics.speed import (
    CalibrationDistanceCheck,
    CameraSpeedConfig,
    SpeedEstimator,
    SpeedResult,
    SpeedSnapshot,
    SpeedTrackStatus,
    queue_progress_speed,
    validate_known_ground_distance,
)
from app.analytics.vertical_queue import (
    VerticalQueueAnalyzer,
    VerticalQueueConfig,
    VerticalQueueRow,
    VerticalQueueSnapshot,
)
from app.analytics.vertical_queue_visualization import (
    annotate_vertical_queues,
    hotter_row_color,
    vertical_row_color,
)

__all__ = [
    "CameraCountingConfig",
    "CameraRestrictedAreaConfig",
    "CameraQueueConfig",
    "CameraSpeedConfig",
    "CalibrationDistanceCheck",
    "CountingResult",
    "CountingSnapshot",
    "CrowdedRegion",
    "HeatmapAccumulator",
    "HeatmapExportPaths",
    "HeatmapGrid",
    "HeatmapSnapshot",
    "HeatmapVideoPaths",
    "HeatmapVideoWriter",
    "LineCount",
    "IntrusionState",
    "IntrusionTrackStatus",
    "OccupancyCount",
    "MovementHeatmaps",
    "MovementHeatmapSnapshot",
    "PeopleCounter",
    "QueueAnalyzer",
    "QueueResult",
    "QueueSnapshot",
    "QueueStatus",
    "QueueTrackState",
    "QueueTrackStatus",
    "RestrictedAreaDetector",
    "RestrictedAreaResult",
    "RestrictedAreaSnapshot",
    "RestrictedZoneStatus",
    "SpeedEstimator",
    "SpeedResult",
    "SpeedSnapshot",
    "SpeedTrackStatus",
    "VerticalQueueAnalyzer",
    "VerticalQueueConfig",
    "VerticalQueueRow",
    "VerticalQueueSnapshot",
    "annotate_people_counts",
    "annotate_crowded_regions",
    "annotate_queues",
    "annotate_restricted_areas",
    "annotate_vertical_queues",
    "colorize_heatmap",
    "export_heatmap_snapshot",
    "export_numeric_grid",
    "hotter_row_color",
    "overlay_heatmap",
    "queue_progress_speed",
    "rank_crowded_regions",
    "validate_known_ground_distance",
    "vertical_row_color",
]
