"""Camera geometry package boundary; implementation begins after Phase 1."""
"""Camera configuration, geometry primitives, and optional calibration."""

from app.geometry.calibration import GroundProjection, ImageToGroundProjector
from app.geometry.config import (
    ActiveSchedule,
    AnalyticsConfig,
    CalibrationConfig,
    CameraConfig,
    CameraConfigError,
    CountingLine,
    DetectorConfig,
    HeatmapConfig,
    NormalizedPoint,
    OutputConfig,
    PolygonZone,
    QueueRegion,
    RestrictedZone,
    ServicePoint,
    TrackerConfig,
    VisualizationConfig,
    dump_camera_config,
    load_camera_config,
)
from app.geometry.primitives import (
    LineCrossing,
    LineCrossingDirection,
    denormalize_point,
    detect_line_crossing,
    line_side,
    point_in_polygon,
    signed_line_side,
    validate_polygon,
)

__all__ = [
    "ActiveSchedule",
    "AnalyticsConfig",
    "CalibrationConfig",
    "CameraConfig",
    "CameraConfigError",
    "CountingLine",
    "DetectorConfig",
    "GroundProjection",
    "HeatmapConfig",
    "ImageToGroundProjector",
    "LineCrossing",
    "LineCrossingDirection",
    "NormalizedPoint",
    "OutputConfig",
    "PolygonZone",
    "QueueRegion",
    "RestrictedZone",
    "ServicePoint",
    "TrackerConfig",
    "VisualizationConfig",
    "denormalize_point",
    "detect_line_crossing",
    "dump_camera_config",
    "line_side",
    "load_camera_config",
    "point_in_polygon",
    "signed_line_side",
    "validate_polygon",
]
